services:
  - type: web
    name: portfolio
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist/dartegnians-portfolio
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 